// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqtr7hL67AoGsTLTGgBXQxBifB7YGezAg',
    appId: '1:316114893899:web:0d603acab93adf18e761ce',
    messagingSenderId: '316114893899',
    projectId: 'frontier-trial',
    authDomain: 'frontier-trial.firebaseapp.com',
    storageBucket: 'frontier-trial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0aKxysmrgGy1VHZBeNuQOc9iDknOPvtM',
    appId: '1:316114893899:android:35a0a3073dfd2994e761ce',
    messagingSenderId: '316114893899',
    projectId: 'frontier-trial',
    storageBucket: 'frontier-trial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADIjYSHReeTPyjCQ6-C32AkvnF4ltyTU0',
    appId: '1:316114893899:ios:1877465d0f138319e761ce',
    messagingSenderId: '316114893899',
    projectId: 'frontier-trial',
    storageBucket: 'frontier-trial.appspot.com',
    iosBundleId: 'com.example.frontierTrial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADIjYSHReeTPyjCQ6-C32AkvnF4ltyTU0',
    appId: '1:316114893899:ios:1877465d0f138319e761ce',
    messagingSenderId: '316114893899',
    projectId: 'frontier-trial',
    storageBucket: 'frontier-trial.appspot.com',
    iosBundleId: 'com.example.frontierTrial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqtr7hL67AoGsTLTGgBXQxBifB7YGezAg',
    appId: '1:316114893899:web:bc12b888e5157e83e761ce',
    messagingSenderId: '316114893899',
    projectId: 'frontier-trial',
    authDomain: 'frontier-trial.firebaseapp.com',
    storageBucket: 'frontier-trial.appspot.com',
  );

}